### ISSUE TITLE
/cowsay cow=sheep renders pretty bad

### ISSUE THREAD

**Issue by jcbee** [guilgaly/cowsay-online#1]
Tried the following command on my company's Slack : `/cowsay cow=sheep Je vends du fromage de Jacques.` and got the following result : 

 _________________________________ 
< Je vends du fromage de Jacques. >
 --------------------------------- ##
##
$the_cow = <<EOC
  \
   \
       __     
      U${eyes}U\.'@@@@@@`.
      \__/(@@@@@@@@@@)
           (@@@@@@@@)
           `YY~~~~YY'
            ||    ||
EOC

I can't express how disappointed I felt at the time. Please, do something, master of code.

**Comment by guilgaly** [comment]
I couldn't let such horrors stand. It should work fine now. 🎉
